def draw_tree():
    print('         *')
    print('        ***')
    print('       *****')
    print('      *******')
    print('     *********')
    print('    ***********')
    print('   *************')
    print('  ***************')
    print(' *****************')
    print('*******************')
    print('         *')
    print('         *')
    print('         *')
    print('         *')
    print('         *')
    print('         *')
    print('         *')
draw_tree()

